// Mocks generated by Mockito 5.4.6 from annotations
// in cookscroll/test/features/recipes/recipe_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cookscroll/features/recipes/data/datasources/meal_db_datasource.dart'
    as _i3;
import 'package:cookscroll/features/recipes/domain/models/recipe.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRecipe_0 extends _i1.SmartFake implements _i2.Recipe {
  _FakeRecipe_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MealDbDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealDbDatasource extends _i1.Mock implements _i3.MealDbDatasource {
  MockMealDbDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Recipe>> searchMeals(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMeals, [query]),
            returnValue: _i4.Future<List<_i2.Recipe>>.value(<_i2.Recipe>[]),
          )
          as _i4.Future<List<_i2.Recipe>>);

  @override
  _i4.Future<List<_i2.Recipe>> getMealsByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getMealsByCategory, [category]),
            returnValue: _i4.Future<List<_i2.Recipe>>.value(<_i2.Recipe>[]),
          )
          as _i4.Future<List<_i2.Recipe>>);

  @override
  _i4.Future<_i2.Recipe?> getMealById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMealById, [id]),
            returnValue: _i4.Future<_i2.Recipe?>.value(),
          )
          as _i4.Future<_i2.Recipe?>);

  @override
  _i4.Future<_i2.Recipe> getRandomMeal() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomMeal, []),
            returnValue: _i4.Future<_i2.Recipe>.value(
              _FakeRecipe_0(this, Invocation.method(#getRandomMeal, [])),
            ),
          )
          as _i4.Future<_i2.Recipe>);

  @override
  _i4.Future<List<String>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);
}
